version: '3.8'

services:
  mysql_db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    ports:
      - "33066:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  laravel_app:
    build: .
    container_name: laravel_app
    restart: always
    depends_on:
      - mysql_db
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    environment:
      - DB_HOST=mysql_db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
